[package]
name = "liven"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.5"
petgraph = "0.6.5"
tantivy = "0.22.0"
tokio = "1.38.0"
tree-sitter = "0.22.6"
tree-sitter-go = "0.21.0"
tree-sitter-typescript = "0.21.1"

[build-dependencies]
cc="*"
